name: Fetch Planes Data

on:
  schedule:
    - cron: '0 */12 * * *' # Run every 12 hours
  workflow_dispatch: # Allow manual trigger

jobs:
  fetch-planes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium

    - name: Run test to fetch planes
      run: npx playwright test tests/fetchPlanes.spec.ts
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
        USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

    - name: Commit and push if there are changes
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add planes.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update planes data - $(date)"
        git push
      
    - name: Upload planes.json as artifact
      uses: actions/upload-artifact@v3
      with:
        name: planes-data
        path: |
          planes.json
          planes_*.json
